### ISSUE TITLE
pygame problems

### ISSUE THREAD

**Issue by reaperMPLS** [reaperMPLS/python#1]
Hello, world! I am wondering how to create a Pygame surface which displays a .png file. I have this code:
#mtg
import pygame, time

pygame.init()
width = 640
height = 480
size = width, height
dis = pygame.display
sur = pygame.Surface
color = (255,16,160)
dis.init()
re = pygame.Rect(0,0,width, height)
sur(size)
dis.set_mode(size)
image = './datbaby.png'
yo = pygame.image.load(image)
dis.set_caption("MTG")
yo.fill(color, re)
pygame.display.update()
time.sleep(3)

it opens a blank screen of the correct size with the correct title, but doesn,t show the file, 'datbaby.png'. Any ideas?

**Comment by sewald00** [comment]
[png_background.txt](https://github.com/reaperMPLS/python/files/1741810/png_background.txt)
I don't know if this is exactly what you are looking for, but it will display the .png and stretch it to the window size.

**Comment by reaperMPLS** [comment]
sewald00
Thank you. I will try this and report back. I don't have Internet at my house, so it'll be a while. Thanks much.

**Comment by reaperMPLS** [comment]
Thank you so much, @sewald00. It works amazingly.

**Comment by sewald00** [comment]
No problem.
